### ISSUE TITLE
Consider renaming

### ISSUE THREAD

**Issue by EricForgy** [MoralisWeb3/Moralis-JS-SDK-v1#10]
### Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK-v1/blob/main/SECURITY.md).
- [x] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK-v1/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).

### Current Limitation

Calling this package `moralis-v1` when there is a v2 makes it seem like this is old tech. v2 is so completely different than v1 that you probably should have used a different name than `moralis`.

I actually think v1 should keep the name `moralis` and v2 should have been called `moralis-server` or something new. v2 is not an evolution of v1. It is a completely different model focused on backends. v1 was actually fine for both clients _and_ servers. I used it in a React SPA as well as a Remix server-side dapp.

My recommendation:
- Keep v1 as `moralis`
- Call v2 `moralis-server` or something new

Otherwise, consider:
- Call v1 `moralis-client` (anything but `moralis-v1` please 🙏)
- Call v2 `moralis-server`

As an aside, it is frustrating to have v2 console warnings when they are not relevant to v1. See #9.

**Comment by ErnoW** [comment]
I understand your concern. The reason for this is the migration of moralis servers towards self-hosted servers, allowing more flexibility in the way you integrate Moralis. This package assumes a parse-server backend, which is not the case anymore in the future, as we are now compatible with any backend.

We will add packages for client-side for popular backends though, but it will look a bit different. Support for example for:
- parse-server (like with v1)
- expressJs
- firebase
- ... more upcoming

These integrations will have both server-side and client-side packages.

With these client-side packages you can call `Moralis.authenticate` or `Moralis.EvmApi.nft.getWalletNFTs` etc. (this is under development at the moment though and a big focus of us to bring the magic back to integrations in client-side apps)

It's a completely new setup, that is more flexible, keeping this package/name intact would conflict that as it is a specific use case (a client-side package for parse-server backend with Moralis)
